# -*- coding: utf-8 -*-
"""AzureOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DGJ_kJzY1X_jmhFGbkJHQqt_TeBHJR4d
"""

import requests
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

subscription_key = '6f564aee8dc44f44b14f01527c99a9bc'
vision_base_url = 'https://labuser25computervision.cognitiveservices.azure.com/vision/v2.0/'
ocr_url = vision_base_url + 'ocr' #ocr을 사용하는 url

image_url = 'https://i.stack.imgur.com/WiDpa.jpg'

image = Image.open(BytesIO(requests.get(image_url).content))

image

headers = {'Ocp-Apim-Subscription-key' : subscription_key}
params = {'language' : 'unk', 'detectOrientation' : 'true'}
data = {'url' : image_url}
response = requests.post(ocr_url, headers = headers, params = params, json = data)

result = response.json()

result

for region in result['regions']:
  lines = region['lines']
  #region:구역
  for line in lines:
    words = line['words']
    for word in words:
      print(word['text'])

image_url = "https://www.unikorea.go.kr/unikorea/common/images/content/peace.png"
image = Image.open(BytesIO(requests.get(image_url).content))
image

headers = {'Ocp-Apim-Subscription-key' : subscription_key}
params = {'language' : 'ko', 'detectOrientation' : 'true'}
data = {'url' : image_url}

response = requests.post(ocr_url, headers = headers, params = params, json = data)
result = response.json()
result

for region in result['regions']:
  lines = region['lines']
  #region:구역
  for line in lines:
    words = line['words']
    for word in words:
      print(word['text'])

